apiVersion: v1
kind: Service
metadata:
  name: kafka-publisher
  labels:
    app: kafka-publisher
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      protocol: TCP
      name: kafka-publisher
  selector:
    app: kafka-publisher